# Generated by Django 6.0.3 on 2026-03-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaCientifica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_area", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_curso", models.CharField(max_length=100)),
                ("apresentacao", models.TextField()),
                ("objetivos", models.TextField()),
                ("competencias", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LinguagemProgramacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_linguagem", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_disciplina", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("semestre", models.CharField(max_length=20)),
                ("ects", models.IntegerField()),
                ("curricularIUnitReadableCode", models.CharField(max_length=100)),
                (
                    "area_cientifica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.areacientifica",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="areacientifica",
            name="disciplinas",
            field=models.ManyToManyField(
                blank=True, related_name="areas_cientificas", to="portfolio.disciplina"
            ),
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_docente", models.CharField(max_length=100)),
                (
                    "disciplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.disciplina",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                ("tecnologias_utilizadas", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        default="default_imagem.jpg", upload_to="projeto_imagens"
                    ),
                ),
                ("video_demo_link", models.URLField(default="")),
                ("github_link", models.URLField(default="")),
                (
                    "disciplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.disciplina",
                    ),
                ),
            ],
        ),
    ]
