# Generated by Django 6.0.4 on 2026-04-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("nivel", models.IntegerField(default=3)),
                ("tipo", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("entidade", models.CharField(blank=True, max_length=100)),
                ("tipo", models.CharField(blank=True, max_length=50)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                ("link_certificado", models.URLField(blank=True)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
            ],
            options={
                "ordering": ["-data_fim", "-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("apresentacao", models.TextField(blank=True)),
                ("objetivos", models.TextField(blank=True)),
                ("competencias", models.TextField(blank=True)),
                ("duracao", models.IntegerField(default=3)),
                ("ects", models.IntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entidade", models.CharField(blank=True, max_length=100)),
                ("titulo", models.CharField(max_length=100)),
                (
                    "trabalho_papel",
                    models.ImageField(blank=True, null=True, upload_to="makingof"),
                ),
                ("decisoes", models.TextField(blank=True)),
                ("erros", models.TextField(blank=True)),
                ("correcoes", models.TextField(blank=True)),
                ("justificacao", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem"),
                            ("framework", "Framework"),
                            ("bd", "Base de Dados"),
                            ("ferramenta", "Ferramenta"),
                            ("outra", "Outra"),
                        ],
                        default="outra",
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("principais_aspetos", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias"),
                ),
                ("nivel_interesse", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("autor", models.CharField(blank=True, max_length=100)),
                ("ano", models.IntegerField(blank=True, null=True)),
                ("resumo", models.TextField(blank=True)),
                ("area_cientifica", models.CharField(blank=True, max_length=100)),
                ("interesse", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("codigo", models.CharField(blank=True, max_length=30)),
                ("ano", models.IntegerField(blank=True, null=True)),
                ("semestre", models.CharField(blank=True, max_length=20)),
                ("ects", models.IntegerField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs")),
            ],
        ),
        migrations.RemoveField(
            model_name="areacientifica",
            name="disciplinas",
        ),
        migrations.RemoveField(
            model_name="disciplina",
            name="area_cientifica",
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="disciplina",
        ),
        migrations.RemoveField(
            model_name="docente",
            name="disciplina",
        ),
        migrations.DeleteModel(
            name="LinguagemProgramacao",
        ),
        migrations.RenameField(
            model_name="docente",
            old_name="nome_docente",
            new_name="nome",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="tecnologias_utilizadas",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="video_demo_link",
        ),
        migrations.AddField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="docente",
            name="pagina_lusofona",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="projeto",
            name="titulo",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="projeto",
            name="video_demo",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="conceitos_aplicados",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="github_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="projetos"),
        ),
        migrations.AddField(
            model_name="projeto",
            name="competencias",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolio.competencia"
            ),
        ),
        migrations.AddField(
            model_name="makingof",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="makingofs",
                to="portfolio.projeto",
            ),
        ),
        migrations.AddField(
            model_name="formacao",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="formacoes", to="portfolio.tecnologia"
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolio.tecnologia"
            ),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(
                blank=True, related_name="unidades_curriculares", to="portfolio.docente"
            ),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="licenciatura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unidades_curriculares",
                to="portfolio.licenciatura",
            ),
        ),
        migrations.AddField(
            model_name="makingof",
            name="unidade_curricular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="makingofs",
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="unidade_curricular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.DeleteModel(
            name="AreaCientifica",
        ),
        migrations.DeleteModel(
            name="Disciplina",
        ),
    ]
