# Generated by Django 6.0.4 on 2026-04-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_competencia_formacao_licenciatura_makingof_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formacao",
            options={},
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="projeto",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="unidade_curricular",
        ),
    ]
