# Generated by Django 6.0.4 on 2026-04-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_formacao_options_remove_makingof_projeto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tecnologia",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="tecnologia",
            name="website",
        ),
    ]
