# Generated by Django 6.0.4 on 2026-04-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_tecnologia_logo_remove_tecnologia_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="pdf",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="tfcs", to="portfolio.tecnologia"
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="area_cientifica",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
