# Generated by Django 6.0.5 on 2026-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0005_tfc_email_tfc_imagem_tfc_licenciatura_tfc_orientador_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=300),
        ),
    ]
