# Generated by Django 6.0.5 on 2026-05-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_tfc_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="area_cientifica",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
